# Spin up a local Postgres database and Adminer instance
version: "3.7"
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: finance
      POSTGRES_PASSWORD: pgfinance
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
  
  app:
    build:
      context: .
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - API_KEY=chsjkv9r01qr5oci2rf0chsjkv9r01qr5oci2rfg
      - POSTGRES_URL=postgresql://db:5432/finance?user=postgres&password=pgfinance

volumes:
  postgres: