# fly.toml app configuration file generated for cs50-finance-plus on 2023-06-01T21:21:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cs50-finance-plus"
primary_region = "dfw"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
